apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-nfs
  labels:
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 159.223.68.139
    path: /srv/nfs/data/pgdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-nfs
  namespace: spring-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: postgres
