apiVersion: v1
kind: Service
metadata:
  name: postgres-h
  namespace: spring-demo
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
